#!/usr/bin/env ruby

REINSTALL_ALL = ARGV[0] == "new"

# shamelessly stolen from https://github.com/tsaleh/dotfiles/blob/master/vim/update_bundles
git_bundles = %w{
  git://github.com/elzr/vim-json.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/pangloss/vim-javascript.git
  git://github.com/tpope/vim-endwise.git
  git://github.com/tpope/vim-git.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-rails.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tomtom/tcomment_vim.git
  git://git.wincent.com/command-t.git
  git://github.com/ervandew/supertab.git
  git@github.com:Lokaltog/vim-easymotion.git
  git@github.com:majutsushi/tagbar.git
  git@github.com:tpope/vim-abolish.git
  git@github.com:tpope/vim-repeat.git
  git@github.com:mhinz/vim-startify.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

if REINSTALL_ALL
  puts "Reinstalling all Vim plugins"
  FileUtils.rm_rf(bundles_dir)
  FileUtils.mkdir(bundles_dir)
end

FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  name = url.split("/").last.split(".").first
  if REINSTALL_ALL
      puts "Installing #{name}"
      `git clone -q #{url}`
  else
    puts "Checking for #{name} #{url}"
    folder_exists = File.directory? name
    if folder_exists
      puts "Plugin already installed"
    else
      puts "Installing #{name} as it doesn't exist"
      `git clone -q #{url}`
    end
  end
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

