#!/usr/bin/env ruby

# shamelessly stolen from https://github.com/tsaleh/dotfiles/blob/master/vim/update_bundles
git_bundles = %w{
  git://github.com/elzr/vim-json.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/pangloss/vim-javascript.git
  git://github.com/tpope/vim-endwise.git
  git://github.com/tpope/vim-git.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-rails.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tomtom/tcomment_vim.git
  git://git.wincent.com/command-t.git
  git://github.com/ervandew/supertab.git
  git@github.com:Lokaltog/vim-easymotion.git
  git@github.com:majutsushi/tagbar.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

