#!/usr/bin/env bash
set -euo pipefail

# Required env vars:
#   REPO                  - owner/repo to work on (e.g. jackfranklin/my-app)
#   ISSUE_NUMBER          - GitHub issue number to implement
#   GH_TOKEN              - fine-grained GitHub PAT scoped to REPO (contents, PRs, issues: read/write)
#   CLAUDE_CODE_OAUTH_TOKEN - long-lived token from `claude setup-token`, tied to your Claude subscription
#   GIT_AUTHOR_NAME        - git user.name to commit as (passed through from the host's git config)
#   GIT_AUTHOR_EMAIL       - git user.email to commit as (passed through from the host's git config)
#
# Optional:
#   BASE_BRANCH    - branch to branch from / PR against (default: main)

: "${REPO:?REPO env var required, e.g. owner/repo}"
: "${ISSUE_NUMBER:?ISSUE_NUMBER env var required}"
: "${GH_TOKEN:?GH_TOKEN env var required}"
: "${CLAUDE_CODE_OAUTH_TOKEN:?CLAUDE_CODE_OAUTH_TOKEN env var required (generate with: claude setup-token)}"
: "${GIT_AUTHOR_NAME:?GIT_AUTHOR_NAME env var required}"
: "${GIT_AUTHOR_EMAIL:?GIT_AUTHOR_EMAIL env var required}"
BASE_BRANCH="${BASE_BRANCH:-main}"

BRANCH="agent/issue-${ISSUE_NUMBER}"
WORKDIR="/work/repo"

TOKEN_LEN="${#CLAUDE_CODE_OAUTH_TOKEN}"
echo "==> CLAUDE_CODE_OAUTH_TOKEN: ${CLAUDE_CODE_OAUTH_TOKEN:0:13}...${CLAUDE_CODE_OAUTH_TOKEN: -4} (length ${TOKEN_LEN})"

echo "==> Cloning ${REPO}"
gh repo clone "${REPO}" "${WORKDIR}" -- --branch "${BASE_BRANCH}"
cd "${WORKDIR}"

echo "==> Configuring git identity and credentials"
git config user.name "${GIT_AUTHOR_NAME}"
git config user.email "${GIT_AUTHOR_EMAIL}"
# gh CLI subcommands pick up GH_TOKEN automatically, but plain `git push` doesn't —
# this wires git's credential helper to shell out to `gh`, which does.
gh auth setup-git

echo "==> Checking out ${BRANCH}"
git checkout -b "${BRANCH}"

echo "==> Fetching issue #${ISSUE_NUMBER}"
ISSUE_BODY="$(gh issue view "${ISSUE_NUMBER}" --repo "${REPO}" --json title,body --jq '"# " + .title + "\n\n" + .body')"

echo "==> Trusting ${WORKDIR} so Claude doesn't prompt or ignore repo settings"
CLAUDE_CONFIG="${HOME}/.claude.json"
[ -f "${CLAUDE_CONFIG}" ] || echo '{}' > "${CLAUDE_CONFIG}"
jq --arg path "${WORKDIR}" '.projects[$path].hasTrustDialogAccepted = true' "${CLAUDE_CONFIG}" > "${CLAUDE_CONFIG}.tmp"
mv "${CLAUDE_CONFIG}.tmp" "${CLAUDE_CONFIG}"

if [ -f package.json ]; then
  echo "==> Installing dependencies"
  # Scoped to just this install step (not a Dockerfile-wide ENV) so postinstall scripts
  # (e.g. Puppeteer downloading Chrome) can run, without silently allowing them for every
  # future npm invocation in every repo this tool ever runs.
  npm install --dangerously-allow-all-scripts
fi

PROMPT="You are working in a clone of ${REPO} on branch ${BRANCH}. Implement the following GitHub issue. Make focused changes, follow existing code conventions, and check package.json for lint/build/test scripts — run whichever are relevant and make sure they pass before finishing. Do not push to ${BASE_BRANCH} directly.

${ISSUE_BODY}"

echo "==> Running claude"
stdbuf -oL claude -p "${PROMPT}" --dangerously-skip-permissions --output-format stream-json --verbose --include-partial-messages \
  | format-claude-stream

if [ -z "$(git status --porcelain)" ]; then
  echo "==> No changes made, nothing to push"
  exit 0
fi

echo "==> Committing and pushing"
git add -A
git commit -m "Implement #${ISSUE_NUMBER}"
git push -u origin "${BRANCH}"

echo "==> Opening PR"
gh pr create \
  --repo "${REPO}" \
  --base "${BASE_BRANCH}" \
  --head "${BRANCH}" \
  --title "Fix #${ISSUE_NUMBER}" \
  --body "Closes #${ISSUE_NUMBER}

Automated PR generated by agent-runner."

echo "==> Done"
