require("winbar").setup({
  show_file_path = true,
  exclude_filetype = {
    "help",
    "startify",
    "terminal",
    "neoterm",
    "dashboard",
    "packer",
    "neogitstatus",
    "fzf",
    "NvimTree",
    "Trouble",
    "alpha",
    "lir",
    "Outline",
    "spectre_panel",
    "toggleterm",
    "qf",
    "",
  },
})
