# get auto completes going
autoload -U compinit
compinit

bindkey '^I' complete-word # complete on tab, leave expansion to _expand

TZ="Europe/London"
HISTFILE=$HOME/.zhistory
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_SPACE
HOSTNAME="`hostname`"
PAGER='less'

LC_ALL='en_US.UTF-8'

GIT_MERGE_AUTOEDIT=no
export GIT_MERGE_AUTOEDIT

# the one true way
export EDITOR='vim'

# emacs style bindings
bindkey -e

# load rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"

# execute binstubs by default
export PATH="./.bundle/binstubs:$PATH"

# export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home"
# export PATH=/opt/apache-maven-3.3.9/bin:$PATH

# heroku toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export AUTOENV_FILE_ENTER=".env"
source $HOME/antigen/antigen.zsh

antigen bundle Tarrasch/zsh-autoenv
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle robbyrussell/oh-my-zsh plugins/z
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# from https://github.com/creationix/nvm#deeper-shell-integration
# place this after nvm initialization!
autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" != "N/A" ] && [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc

# z plugin gets aliased to `j`
alias j="z"

# so autoenv runs all the time, even when you open a tmux split
cd .

source $HOME/dotfiles/zsh/aliases
source $HOME/dotfiles/zsh/functions
# source $HOME/dotfiles/zsh/prompt
source $HOME/dotfiles/zsh/secret

autoload -U promptinit; promptinit
prompt pure

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='ag -g "" --hidden'

# export GOPATH=$HOME/git/go
# export PATH="$GOPATH/bin:$PATH"

# put things in ~/.bin into my $PATH
export PATH="$HOME/.bin:$PATH"

# execute locally installed npm modules
# export PATH="./node_modules/.bin:$PATH"

# yarn
# export PATH="$PATH:`yarn global bin`"

# export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export WORKON_HOME="$HOME/.virtualenvs"
export PROJECT_HOME="$HOME/git/thread"
export VIRTUALENVWRAPPER_PYTHON=`which python3`
export PATH="$PATH:$HOME/.rbenv/bin"

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
  source /usr/local/bin/virtualenvwrapper.sh
fi



case `uname` in
  Darwin)
    # Mac things here
    export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
  ;;
  Linux)
    # commands for Linux go here
  ;;
esac
